# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asthma.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 740)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 10, 511, 671))
        self.label.setStyleSheet("border-image: url(:/a1/asthama.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 341, 671))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(249, 242, 173, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 20, 621, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 90, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 90, 131, 131))
        self.label_5.setStyleSheet("border-image: url(:/s1/s1.jpg);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 280, 121, 121))
        self.label_6.setStyleSheet("border-image: url(:/s5/s6.jpg);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, 170, 131, 131))
        self.label_7.setStyleSheet("border-image: url(:/s2/s2.jpg);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(210, 360, 131, 131))
        self.label_8.setStyleSheet("border-image: url(:/s6/s7.jpg);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 460, 121, 121))
        self.label_9.setStyleSheet("border-image: url(:/s3/s3.jpg);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(210, 550, 131, 121))
        self.label_10.setStyleSheet("border-image: url(:/newPrefix/s5.jpg);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.age_label = QtWidgets.QLabel(self.centralwidget)
        self.age_label.setGeometry(QtCore.QRect(390, 130, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.age_label.setFont(font)
        self.age_label.setObjectName("age_label")
        self.gender_label = QtWidgets.QLabel(self.centralwidget)
        self.gender_label.setGeometry(QtCore.QRect(390, 170, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.gender_label.setFont(font)
        self.gender_label.setObjectName("gender_label")
        self.coughing_label = QtWidgets.QLabel(self.centralwidget)
        self.coughing_label.setGeometry(QtCore.QRect(390, 210, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.coughing_label.setFont(font)
        self.coughing_label.setObjectName("coughing_label")
        self.wheezing_label = QtWidgets.QLabel(self.centralwidget)
        self.wheezing_label.setGeometry(QtCore.QRect(390, 250, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.wheezing_label.setFont(font)
        self.wheezing_label.setObjectName("wheezing_label")
        self.shortnessofbreath_label = QtWidgets.QLabel(self.centralwidget)
        self.shortnessofbreath_label.setGeometry(QtCore.QRect(390, 290, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.shortnessofbreath_label.setFont(font)
        self.shortnessofbreath_label.setObjectName("shortnessofbreath_label")
        self.chesttightning_label = QtWidgets.QLabel(self.centralwidget)
        self.chesttightning_label.setGeometry(QtCore.QRect(390, 330, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.chesttightning_label.setFont(font)
        self.chesttightning_label.setObjectName("chesttightning_label")
        self.rapidbreathing_label = QtWidgets.QLabel(self.centralwidget)
        self.rapidbreathing_label.setGeometry(QtCore.QRect(390, 370, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.rapidbreathing_label.setFont(font)
        self.rapidbreathing_label.setObjectName("rapidbreathing_label")
        self.fatigue_label = QtWidgets.QLabel(self.centralwidget)
        self.fatigue_label.setGeometry(QtCore.QRect(390, 410, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.fatigue_label.setFont(font)
        self.fatigue_label.setObjectName("fatigue_label")
        self.troublesleeping_label = QtWidgets.QLabel(self.centralwidget)
        self.troublesleeping_label.setGeometry(QtCore.QRect(390, 450, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.troublesleeping_label.setFont(font)
        self.troublesleeping_label.setObjectName("troublesleeping_label")
        self.symworsenactivity_label = QtWidgets.QLabel(self.centralwidget)
        self.symworsenactivity_label.setGeometry(QtCore.QRect(390, 490, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.symworsenactivity_label.setFont(font)
        self.symworsenactivity_label.setObjectName("symworsenactivity_label")
        self.symworsenallegry_label = QtWidgets.QLabel(self.centralwidget)
        self.symworsenallegry_label.setGeometry(QtCore.QRect(390, 530, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.symworsenallegry_label.setFont(font)
        self.symworsenallegry_label.setObjectName("symworsenallegry_label")
        self.predict_button = QtWidgets.QPushButton(self.centralwidget)
        self.predict_button.setGeometry(QtCore.QRect(580, 580, 131, 51))

        
        
        self.predict_button.clicked.connect(self.predict_diagnosis)

        

        self.df = pd.read_csv('D:\Vaibhavi\Asthama_Dataset.csv')
        self.X = self.df[['Age', 'Gender', 'Coughing', 'Wheezing', 'Shortness of breath',
                          'Chest Tightning', 'Rapid Breathing', 'Fatigue', 'Trouble Sleeping',
                          'Symptoms worsen with activity', 'Symptoms worsen with allergy']]
        self.y = self.df['Diagnosis']
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(self.X, self.y,
                                                                                test_size=0.2, random_state=42)
        self.model = GaussianNB()
        self.model.fit(self.X_train, self.y_train)

        
        
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.predict_button.setFont(font)
        self.predict_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(244, 196, 87, 255), stop:1 rgba(255, 255, 255, 255));")
        self.predict_button.setObjectName("predict_button")
        self.diagosis_label = QtWidgets.QLabel(self.centralwidget)
        self.diagosis_label.setGeometry(QtCore.QRect(390, 640, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.diagosis_label.setFont(font)
        self.diagosis_label.setObjectName("diagosis_label")
        self.age_input = QtWidgets.QLineEdit(self.centralwidget)
        self.age_input.setGeometry(QtCore.QRect(770, 130, 113, 22))
        self.age_input.setObjectName("age_input")
        self.gender_input = QtWidgets.QLineEdit(self.centralwidget)
        self.gender_input.setGeometry(QtCore.QRect(770, 170, 113, 22))
        self.gender_input.setObjectName("gender_input")
        self.coughing_input = QtWidgets.QLineEdit(self.centralwidget)
        self.coughing_input.setGeometry(QtCore.QRect(770, 210, 113, 22))
        self.coughing_input.setObjectName("coughing_input")
        self.wheezing_input = QtWidgets.QLineEdit(self.centralwidget)
        self.wheezing_input.setGeometry(QtCore.QRect(770, 250, 113, 22))
        self.wheezing_input.setObjectName("wheezing_input")
        self.shortnessofbreath_input = QtWidgets.QLineEdit(self.centralwidget)
        self.shortnessofbreath_input.setGeometry(QtCore.QRect(770, 290, 113, 22))
        self.shortnessofbreath_input.setObjectName("shortnessofbreath_input")
        self.chesttightning_input = QtWidgets.QLineEdit(self.centralwidget)
        self.chesttightning_input.setGeometry(QtCore.QRect(770, 330, 113, 22))
        self.chesttightning_input.setObjectName("chesttightning_input")
        self.rapidbreathing_input = QtWidgets.QLineEdit(self.centralwidget)
        self.rapidbreathing_input.setGeometry(QtCore.QRect(770, 370, 113, 22))
        self.rapidbreathing_input.setObjectName("rapidbreathing_input")
        self.fatigue_input = QtWidgets.QLineEdit(self.centralwidget)
        self.fatigue_input.setGeometry(QtCore.QRect(770, 410, 113, 22))
        self.fatigue_input.setObjectName("fatigue_input")
        self.troublesleeping_input = QtWidgets.QLineEdit(self.centralwidget)
        self.troublesleeping_input.setGeometry(QtCore.QRect(770, 450, 113, 22))
        self.troublesleeping_input.setObjectName("troublesleeping_input")
        self.symworsenactivity_input = QtWidgets.QLineEdit(self.centralwidget)
        self.symworsenactivity_input.setGeometry(QtCore.QRect(770, 490, 113, 22))
        self.symworsenactivity_input.setObjectName("symworsenactivity_input")
        self.symworsenallegry_input = QtWidgets.QLineEdit(self.centralwidget)
        self.symworsenallegry_input.setGeometry(QtCore.QRect(770, 530, 113, 22))
        self.symworsenallegry_input.setObjectName("symworsenallegry_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", " CHILDHOOD ASTHMA PREDICTION "))
        self.label_4.setText(_translate("MainWindow", "Enter your Symptoms:"))
        self.age_label.setText(_translate("MainWindow", "AGE"))
        self.gender_label.setText(_translate("MainWindow", "GENDER"))
        self.coughing_label.setText(_translate("MainWindow", "COUGHING (Yes/No)"))
        self.wheezing_label.setText(_translate("MainWindow", "WHEEZING (Yes/No)"))
        self.shortnessofbreath_label.setText(_translate("MainWindow", "SHORTNESS OF BREATH (Yes/No)"))
        self.chesttightning_label.setText(_translate("MainWindow", "CHEST TIGHTNING (Yes/No)"))
        self.rapidbreathing_label.setText(_translate("MainWindow", "RAPID BREATHING (Yes/No)"))
        self.fatigue_label.setText(_translate("MainWindow", "FATIGUE (Yes/No)"))
        self.troublesleeping_label.setText(_translate("MainWindow", "TROUBLE SLEEPING (Yes/No)"))
        self.symworsenactivity_label.setText(_translate("MainWindow", "SYMPTOMS WORSEN WITH ACITIVITY (Yes/No)"))
        self.symworsenallegry_label.setText(_translate("MainWindow", "SYMPTOMS WORSEN WITH ALLEGRY (Yes/No)"))
        self.predict_button.setText(_translate("MainWindow", "PREDICT"))
        self.diagosis_label.setText(_translate("MainWindow", "DIAGNOSIS"))


            
                    




    def predict_diagnosis(self):
        
        age = int(self.age_input.text())
        gender = self.gender_input.text()
        coughing = self.coughing_input.text()
        wheezing = self.wheezing_input.text()
        shortness_of_breath = self.shortnessofbreath_input.text()
        chest_tightening = self.chesttightning_input.text()
        rapid_breathing = self.rapidbreathing_input.text()
        fatigue = self.fatigue_input.text()
        trouble_sleeping = self.troublesleeping_input.text()
        symptoms_worsen_with_activity = self.symworsenactivity_input.text()
        symptoms_worsen_with_allergy = self.symworsenallegry_input.text()

        
        input_data = pd.DataFrame({
        'Age': [age],
        'Gender': [gender],
        'Coughing': [coughing],
        'Wheezing': [wheezing],
        'Shortness of breath': [shortness_of_breath],
        'Chest Tightning': [chest_tightening],
        'Rapid Breathing': [rapid_breathing],
        'Fatigue': [fatigue],
        'Trouble Sleeping': [trouble_sleeping],
        'Symptoms worsen with activity': [symptoms_worsen_with_activity],
        'Symptoms worsen with allergy': [symptoms_worsen_with_allergy]
        })

        
        input_data = input_data.replace({'Yes': 1, 'No': 0, 'Male': 1, 'Female': 2})

       
        prediction = self.model.predict(input_data)

        
        if prediction == 1:
            diagnosis = "Diagnosis: Yes, asthma is present."
        else:
            diagnosis = "Diagnosis: No, there is no asthma."
        self.diagosis_label.setText(diagnosis)
        

import a1rc
import s1rc
import s2rc
import s3rc
import s4rc
import s5rc
import s6rc
       
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
